class AuthException(Exception):
    ...

class UserNotFoundException(AuthException):
    ...

class UserAlreadyExistsException(AuthException):
    ...

class UserNotVerificatedException(AuthException):
    ...

class UserAlreadyVerificatedException(AuthException):
    ...

class UserBannedException(AuthException):
    ...

class InvalidPasswordException(AuthException):
    ...

class InvalidTokenTypeException(AuthException):
    ...

class InvalidOTPException(AuthException):
    ...

class TokenExpireException(AuthException):
    ...

class NotJSONResponseException(AuthException):
    ...

class MissingIDTokenException(AuthException):
    ...

    
