class LinkException(Exception):
    ...

class LinkNotFoundException(LinkException):
    ...

class ShortLinkNotFoundException(LinkException):
    ...

class NotValidURLException(LinkException):
    ...
